# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package pruss;
use base qw(Exporter);
use base qw(DynaLoader);
package prussc;
bootstrap pruss;
package pruss;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package pruss;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package pruss;


############# Class : pruss::PRU ##############

package pruss::PRU;
use vars qw(@ISA %OWNER %ITERATORS %BLESSEDMEMBERS);
@ISA = qw( pruss );
%OWNER = ();
%ITERATORS = ();
sub new {
    my $pkg = shift;
    my $self = prussc::new_PRU(@_);
    bless $self, $pkg if defined($self);
}

*modprobe = *prussc::PRU_modprobe;
*modunprobe = *prussc::PRU_modunprobe;
*enable = *prussc::PRU_enable;
*disable = *prussc::PRU_disable;
*reset = *prussc::PRU_reset;
*load = *prussc::PRU_load;
*set_channel = *prussc::PRU_set_channel;
*get_state = *prussc::PRU_get_state;
*send_msg = *prussc::PRU_send_msg;
*get_msg = *prussc::PRU_get_msg;
*wait_for_event = *prussc::PRU_wait_for_event;
*mem_writeint = *prussc::PRU_mem_writeint;
*mem_readint = *prussc::PRU_mem_readint;
sub DESTROY {
    return unless $_[0]->isa('HASH');
    my $self = tied(%{$_[0]});
    return unless defined $self;
    delete $ITERATORS{$self};
    if (exists $OWNER{$self}) {
        prussc::delete_PRU($self);
        delete $OWNER{$self};
    }
}

sub DISOWN {
    my $self = shift;
    my $ptr = tied(%$self);
    delete $OWNER{$ptr};
}

sub ACQUIRE {
    my $self = shift;
    my $ptr = tied(%$self);
    $OWNER{$ptr} = 1;
}


# ------- VARIABLE STUBS --------

package pruss;

*PRU_OFFLINE = *prussc::PRU_OFFLINE;
*PRU_RUNNING = *prussc::PRU_RUNNING;
*PRU_HALTED = *prussc::PRU_HALTED;
*SYSFS_PATH = *prussc::SYSFS_PATH;
*FW_PATH = *prussc::FW_PATH;
*RPMSG_PATH = *prussc::RPMSG_PATH;
*PRU_ICSS = *prussc::PRU_ICSS;
*PRU_ICSS_LEN = *prussc::PRU_ICSS_LEN;
*PRU_DRAM0 = *prussc::PRU_DRAM0;
*PRU_DRAM1 = *prussc::PRU_DRAM1;
*PRU_SRAM = *prussc::PRU_SRAM;
1;
